import asyncio
import nest_asyncio
import json
import os
from pydantic import AnyUrl
from autogen_ext.tools.mcp import SseServerParams, StreamableHttpServerParams, mcp_server_tools
from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient
from autogen_core.memory import ListMemory, MemoryContent
from autogen_core import CancellationToken
from autogen_core.tools import FunctionTool
from mcp import ClientSession, types
from mcp.client.sse import sse_client
from mcp.client.streamable_http import streamablehttp_client
from typing import Dict, Any
from dotenv import load_dotenv

load_dotenv()

nest_asyncio.apply()

prompt = "Find a dataset for pickup truck sales in US in the year 2024. Proceed with purchasing dataset and finally retrieve the contents and summarize the dataset before making a presentation."

print("\n*-------------------------------------------------------------------------------------------------------------------------------------------------*")
print("Agent Task")
print("*-------------------------------------------------------------------------------------------------------------------------------------------------*")
print("Agent triggered for user prompt: " + prompt)
print("\n*-------------------------------------------------------------------------------------------------------------------------------------------------*")
print("Agent Execution Steps")
print("*-------------------------------------------------------------------------------------------------------------------------------------------------*")

# description for each tool used in result display
textConfig = {
  "find-seller":
    "I will use Skyfire's find-seller tool to find a seller for the requested data & retrieve the MCP server URL of the seller",
  "create-kya-token":
    "I will use Skyfire's create-kya-token tool to create a KYA token for myself",
  "create-payment-token":
    "I will use Skyfire's create-payment-token tool to create a PAY token for the dataset which is later used by receiver to claim payment",
  "create-account-and-login":
    "I will use Dappier's create-account-and-login tool to create account and login myself using the KYA token from Skyfire and a password generated by me",
  "search-dataset":
    "I will use Dappier's search-dataset tool to find the right dataset",
  "get-pricing":
    "I will use Dappier's get-pricing tool to get the price of dataset ",
  "download-dataset":
    "I will use Dappier's download-dataset tool to pay Dappier and get the download URL of the data",
  "retrieve-file-content":
    "I will use Visualisation's retrieve-file-content tool to get the data and create a brief summary",
  "upload-csv":
    "I will use Visualisation's upload-csv tool to upload csv data to Google Sheets and create a chart",
  "connects_to_mcp_server": "Installing MCP server",
};

async def run_agent() -> None:
    # Get all available tools and resources
    all_servers = agent_context["available_mcp_servers"] + agent_context["dynamically_mounted_server"]
    result = await collect_tools_resources_from_servers(all_servers)
    all_tools = result["all_tools"]
    all_resources = result["all_resources"]

    # Add resources to memory
    await memory.add(MemoryContent(
        content=", ".join(all_resources),
        mime_type="text/plain",
        metadata={"role": "assistant"}
    ))

    # Create an agent with all tools and memory
    agent = AssistantAgent(
        name="autogen_commerce_agent",
        model_client=OpenAIChatCompletionClient(
            model="gpt-4o",
            api_key=os.getenv("OPENAI_API_KEY"),
            ),
        tools=all_tools,
        memory=[memory],
        reflect_on_tool_use=True,
        max_tool_iterations=20,
        system_message="You are a helpful e-commerce buyer agent assisting user to make a purchase. Whenever there is a need to create an account, use 123456S$d#d as the password. Do no truncate or mutate tokens. IMPORTANT: Do not assume dataset URLs and pricing."
        # For the scope of this demo, the agent is instructed to use a static password for account creation and login. As an improvisation in future, the agent could randomly generate a password and store in agent memory and also share it with human using secure password services like 1Password, Keeper etc.
    )
    result = await agent.run(task="Find a dataset for pickup truck sales in US in the year 2024. Proceed with purchasing dataset and finally retrieve the contents and summarize the dataset before making a presentation.", cancellation_token=CancellationToken())

    await add_steps_to_memory(result)

    # Check for tool name connects_to_mcp_server and re-trigger the agent
    new_tools_found  = await checkAndUpdateAgentContextIfMCPConnectionIsInitiated(result)

    if new_tools_found:
        await run_agent()

async def connects_to_mcp_server(mcpServerUrl: str, sellerName: str) -> str:
    """Connects to the seller MCP server URL"""
    return f"Connected to seller '{sellerName}' at '{mcpServerUrl}'"

connect_mcp_server_tool = FunctionTool(connects_to_mcp_server, description="Connects to the seller MCP server URL")
agent_context = {
    "available_mcp_servers": [
        StreamableHttpServerParams(
            url = os.getenv("SKYFIRE_MCP_SERVER_URL"),
            headers = {
                "skyfire-api-key": os.getenv("SKYFIRE_API_KEY")
            },
        ),
        StreamableHttpServerParams(
            url = os.getenv("REPORTING_MCP_SERVER_URL"),
            headers = {}
        )
    ],
    "dynamically_mounted_server": []
}

#  initialize memory to pass between multiple agent triggers
memory = ListMemory()
async def collect_tools_resources_from_servers(all_servers) -> Dict[str, Any]:
    """Collects tools and resources from multiple MCP servers."""
    all_tools = [connect_mcp_server_tool]
    all_resources = []
    for server in all_servers:
        tools = await mcp_server_tools(server)
        all_tools.extend(tools)
        resources = await get_all_resources(server.url, server.headers)
        all_resources.append(resources)
    return {"all_tools": all_tools, "all_resources": all_resources}

async def add_steps_to_memory(result) -> None:
    # We'll pair ToolCallRequestEvent and ToolCallExecutionEvent by tool name
    # Adds formatting for readable results
    pending_tool_calls = {}
    output_logs = []
    for msg in result.messages:
        role = "assistant" if msg.source != "user" else "user"
        bullet = "\u2022"  # Unicode bullet
        if msg.type == "ToolCallRequestEvent":
            for fc in msg.content:
                # Store input info for this tool call
                pending_tool_calls[fc.name] = {
                    "role": role,
                    "input": fc.arguments,
                    "desc": textConfig.get(fc.name)
                }
        elif msg.type == "ToolCallExecutionEvent":
            for res in msg.content:
                # Try to find matching input
                call = pending_tool_calls.pop(res.name, None)
                pretty_log = []
                pretty_log.append(f"{bullet} Role: {role}")
                pretty_log.append(f"    Tool: {res.name}")
                desc = textConfig.get(res.name) or (call["desc"] if call else None)
                if desc:
                    pretty_log.append(f"      Description: {desc}")
                if call and call["input"]:
                    # Try to pretty print input if it's JSON
                    try:
                        input_obj = json.loads(call["input"]) if isinstance(call["input"], str) else call["input"]
                        pretty_input = json.dumps(input_obj, indent=8)
                        pretty_log.append(f"      Input: {pretty_input}")
                    except Exception:
                        pretty_log.append(f"      Input: {call['input']}")
                # Pretty print output if it's JSON
                try:
                    output_obj = json.loads(res.content) if isinstance(res.content, str) else res.content
                    pretty_output = json.dumps(output_obj, indent=4)
                    pretty_log.append(f"      Output: {pretty_output}")
                except Exception:
                    pretty_log.append(f"      Output: {res.content}")
                log_str = "\n".join(pretty_log)
                print(log_str + "\n*------------------------------------------------------------------------------------*\n")
                output_logs.append((log_str, role))
        elif msg.type == "TextMessage":
            pretty_log = [f"{bullet} Role: {role}", f"    Text: {msg.content}"]
            log_str = "\n".join(pretty_log)
            output_logs.append((log_str, role))
            if role != "user":
                print(log_str + "\n*------------------------------------------------------------------------------------*\n")
        elif msg.type == "MemoryQueryEvent":
            continue #skipping memory being displayed in the final output_logs
        else:
            pretty_log = [f"{bullet} Role: {role}", f"    Raw: {str(msg)}"]
            log_str = "\n".join(pretty_log)
            print(log_str + "\n*------------------------------------------------------------------------------------*\n")
            output_logs.append((log_str, role))

    # Add all logs to memory
    for log_str, role in output_logs:
        await memory.add(MemoryContent(
            content=log_str,
            mime_type="text/plain",
            metadata={"role": role}
        ))

async def checkAndUpdateAgentContextIfMCPConnectionIsInitiated(result) -> bool:
    new_tools_found = False
    for message in result.messages:
        if message.type == "ToolCallRequestEvent" and not new_tools_found:
            for content in message.content:
                if content.name == 'connects_to_mcp_server':
                    new_tools_found = True
                    agent_context["dynamically_mounted_server"] = [StreamableHttpServerParams(url = json.loads(content.arguments)["mcpServerUrl"], headers = {})]
                    await memory.add(MemoryContent(
                        content="Role: Assistant, Text: You are now connected to the tools provided by the seller MCP server as well, run tools as per input prompt to solve problems step by step.",
                        mime_type="text/plain",
                        metadata={"role": "system"}
                    ))
                    break

    return new_tools_found

async def get_all_resources(url, headers) -> str:
    """Get all resources from an MCP server using appropriate client based on URL"""
    try:

        client_context = streamablehttp_client(url, headers or {})
        
        # Get streams - handle both 2-tuple (SSE) and 3-tuple (HTTP)
        async with client_context as streams:
            read, write = streams[0], streams[1]  # Take first two values regardless
            
            async with ClientSession(read, write) as session:
                # Initialize the connection
                await session.initialize()
                try:
                    # List available resources
                    resources = await session.list_resources()
                    # Read a resource
                    resource_content = await session.read_resource(AnyUrl(resources.resources[0].uri))
                    content_block = resource_content.contents[0]
                    if isinstance(content_block, types.TextResourceContents):
                        return content_block.text
                except:
                    return ""
    except Exception as e:
        print(f"Error fetching resources from {url}: {e}")
        return ""

async def initial_run():
    await memory.add(MemoryContent(
        content="Role: Assistant, Text: You are a e-commerce buyer agent assisting user to make a purchase. When connects_to_mcp_server tool is executed, stop the processing",
        mime_type="text/plain",
        metadata={"role": "system"}
    ))
    await run_agent()

if __name__ == "__main__":
    asyncio.run(initial_run())